=== decentralized-identity/hatpro-schema-htwg/packages/core/json/schemas/TravelProfile.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.example.org/hatpro/core/TravelProfile.schema.json",
  "title": "TravelProfile",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "hatproIdentifier": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/HATProIdentifier.schema.json"
    },
    "version": {
      "default": "0.1.0",
      "pattern": "^\\d+\\.\\d+\\.\\d+(-[A-Za-z0-9.-]+)?$",
      "type": "string"
    },
    "names": {
      "description": "structured name expressions for this traveler",
      "type": "array",
      "items": {
        "$ref": "https://schemas.example.org/hatpro/name/Name.schema.json"
      }
    },
    "personalCommInfo": {
      "description": "personal communication properties",
      "$ref": "https://schemas.example.org/hatpro/personalCommInfo/PersonalCommInfo.schema.json"
    },
    "physicalLocation": {
      "description": "personal locations and addresses",
      "$ref": "https://schemas.example.org/hatpro/physicalLocation/PhysicalLocation.schema.json"
    }
  },
  "required": [
    "version",
    "hatproIdentifier",
    "personalCommInfo"
  ]
}

=== decentralized-identity/hatpro-schema-htwg/packages/core/json/templates/TravelProfile.template.json
{
  "hatproIdentifier": {
    "uuid7": "",
    "verifiableIdentifier": ""
  },
  "version": "0.1.0",
  "names": [
    {
      "namePurpose": {
        "value": "",
        "languageConfiguration": {
          "langLocale": {
            "langLocale": "en-US"
          },
          "encoding": {
            "encoding": "UTF-8"
          }
        }
      },
      "languageConfig": {
        "langLocale": {
          "langLocale": "en-US"
        },
        "encoding": {
          "encoding": "UTF-8"
        }
      },
      "firstGivenName": {
        "value": "",
        "languageConfiguration": {
          "langLocale": {
            "langLocale": "en-US"
          },
          "encoding": {
            "encoding": "UTF-8"
          }
        }
      },
      "secondGivenName": {
        "value": "",
        "languageConfiguration": {
          "langLocale": {
            "langLocale": "en-US"
          },
          "encoding": {
            "encoding": "UTF-8"
          }
        }
      },
      "firstSurname": {
        "value": "",
        "languageConfiguration": {
          "langLocale": {
            "langLocale": "en-US"
          },
          "encoding": {
            "encoding": "UTF-8"
          }
        }
      },
      "secondSurname": {
        "value": "",
        "languageConfiguration": {
          "langLocale": {
            "langLocale": "en-US"
          },
          "encoding": {
            "encoding": "UTF-8"
          }
        }
      },
      "sortName": {
        "value": "",
        "languageConfiguration": {
          "langLocale": {
            "langLocale": "en-US"
          },
          "encoding": {
            "encoding": "UTF-8"
          }
        }
      },
      "nameTitles": {
        "items": [
          ""
        ]
      },
      "nameSuffixes": {
        "items": [
          ""
        ]
      },
      "nameDisplays": {
        "layoutDescription": {
          "value": "",
          "languageConfiguration": {
            "langLocale": {
              "langLocale": "en-US"
            },
            "encoding": {
              "encoding": "UTF-8"
            }
          }
        },
        "items": [
          {
            "formatName": {
              "value": "",
              "languageConfiguration": {
                "langLocale": {
                  "langLocale": "en-US"
                },
                "encoding": {
                  "encoding": "UTF-8"
                }
              }
            },
            "formatDescription": {
              "value": "",
              "languageConfiguration": {
                "langLocale": {
                  "langLocale": "en-US"
                },
                "encoding": {
                  "encoding": "UTF-8"
                }
              }
            },
            "nameFormatScript": {
              "items": [
                {
                  "component": "",
                  "separator": ""
                }
              ]
            }
          }
        ]
      }
    }
  ],
  "personalCommInfo": {
    "preferredSpokenLanguages": [
      {
        "languageLocale": {
          "langLocale": "en-US"
        },
        "proficiencyLevel": 0,
        "ranking": 0
      }
    ],
    "preferredWrittenLanguages": [
      {
        "languageLocale": {
          "langLocale": "en-US"
        },
        "proficiencyLevel": 0,
        "ranking": 0
      }
    ],
    "prefDistanceUnit": "",
    "prefTimeUnit": "",
    "prefTemperatureUnit": "",
    "currencyPreferences": {
      "prefDispCurrency": "",
      "prefSettlmentCurrency": ""
    }
  }
}
