=== decentralized-identity/hatpro-schema-htwg/packages/name/json/schemas/Name.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.example.org/hatpro/name/Name.schema.json",
  "title": "\"Name\"",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "namePurpose": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/InternationalString.schema.json"
    },
    "languageConfig": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/LanguageConfiguration.schema.json"
    },
    "firstGivenName": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/InternationalString.schema.json"
    },
    "secondGivenName": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/InternationalString.schema.json"
    },
    "firstSurname": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/InternationalString.schema.json"
    },
    "secondSurname": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/InternationalString.schema.json"
    },
    "sortName": {
      "$ref": "https://schemas.example.org/hatpro/core/commonLib/InternationalString.schema.json"
    },
    "nameTitles": {
      "$ref": "https://schemas.example.org/hatpro/name/NameTitles.schema.json"
    },
    "nameSuffixes": {
      "$ref": "https://schemas.example.org/hatpro/name/NameSuffixes.schema.json"
    },
    "nameDisplays": {
      "$ref": "https://schemas.example.org/hatpro/name/NameDisplayLayouts.schema.json"
    }
  }
}

=== decentralized-identity/hatpro-schema-htwg/packages/name/json/templates/Name.template.json
{
  "namePurpose": {
    "value": "",
    "languageConfiguration": {
      "langLocale": {
        "langLocale": "en-US"
      },
      "encoding": {
        "encoding": "UTF-8"
      }
    }
  },
  "languageConfig": {
    "langLocale": {
      "langLocale": "en-US"
    },
    "encoding": {
      "encoding": "UTF-8"
    }
  },
  "firstGivenName": {
    "value": "",
    "languageConfiguration": {
      "langLocale": {
        "langLocale": "en-US"
      },
      "encoding": {
        "encoding": "UTF-8"
      }
    }
  },
  "secondGivenName": {
    "value": "",
    "languageConfiguration": {
      "langLocale": {
        "langLocale": "en-US"
      },
      "encoding": {
        "encoding": "UTF-8"
      }
    }
  },
  "firstSurname": {
    "value": "",
    "languageConfiguration": {
      "langLocale": {
        "langLocale": "en-US"
      },
      "encoding": {
        "encoding": "UTF-8"
      }
    }
  },
  "secondSurname": {
    "value": "",
    "languageConfiguration": {
      "langLocale": {
        "langLocale": "en-US"
      },
      "encoding": {
        "encoding": "UTF-8"
      }
    }
  },
  "sortName": {
    "value": "",
    "languageConfiguration": {
      "langLocale": {
        "langLocale": "en-US"
      },
      "encoding": {
        "encoding": "UTF-8"
      }
    }
  },
  "nameTitles": {
    "items": [
      ""
    ]
  },
  "nameSuffixes": {
    "items": [
      ""
    ]
  },
  "nameDisplays": {
    "layoutDescription": {
      "value": "",
      "languageConfiguration": {
        "langLocale": {
          "langLocale": "en-US"
        },
        "encoding": {
          "encoding": "UTF-8"
        }
      }
    },
    "items": [
      {
        "formatName": {
          "value": "",
          "languageConfiguration": {
            "langLocale": {
              "langLocale": "en-US"
            },
            "encoding": {
              "encoding": "UTF-8"
            }
          }
        },
        "formatDescription": {
          "value": "",
          "languageConfiguration": {
            "langLocale": {
              "langLocale": "en-US"
            },
            "encoding": {
              "encoding": "UTF-8"
            }
          }
        },
        "nameFormatScript": {
          "items": [
            {
              "component": "",
              "separator": ""
            }
          ]
        }
      }
    ]
  }
}
